name: Auto-Script

on:
  schedule:
  - cron: "0 */2 * * *"
  workflow_dispatch:

env:
  GH_USERNAME: ${{ secrets.GH_USERNAME }}
  GH_MAIL: ${{ secrets.GH_MAIL }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       - name: Checkout
         uses: actions/checkout@v3

       - name: Setup Python
         uses: actions/setup-python@v4
         with:
           python-version: '3.10'

       - name: Install Python Packages
         run: |
           python -m pip install --upgrade pip
           pip install requests

       - name: Running The Script
         continue-on-error: true
         run: python3 main.py

       - name: Change config.json
         run: bash commit.sh
